## KNN算法   K近邻

有监督学习，标签

分类：投票

回归：均值

k值过小，过拟合；k值过大，欠拟合

## 欧式距离
对应维度的平方和，开平方根

## 曼哈顿距离，城市街区距离
对应维度的绝对值和，求和

## 切比雪夫距离
在曼哈顿距离的基础上，加上可以斜着走
对应维度的绝对值，求最大值

## 闵可夫斯基距离
不是一种新的距离的度量方式
是对多个距离度量公式的概括性的表达


## 特征预处理

    归一化：通过对原始数据进行变换，把数据的值映射到【min, max】（默认[0, 1]）之间
        可能受到特殊值的影响
        通过公式把 各列的值映射到 【0, 1】之间
        x' = (当前值 - 该列最小值) / (该列最大值 - 该列最小值)
        x'' = x' * (max - min) + min
    弊端：易受到最大值和最小值的影响，一般用于处理 小数据集

    标准化：通过对原始数据进行变换，为均值为0 标准差为1 的标志正态分布的数据
        通过公式把 各列的值映射到 【-1, 1】之间
        x' = (当前值 - 该列均值) / 该列标准差
        x'' = x' * 2 + 1

    无论是归一化还是标准化，目的都是为了解决 模型量纲（单位）问题，导致模型评估低等问题


## 交叉验证
    一种数据分割的方法，将训练集分为 n 份，拿一份做验证机（测试集），其他n-1份做训练集

## 网格搜索
    优化超参数的一种方法，模型调参的有效工具   
    交叉验证评估

### 交叉验证网格搜索API
    sklearn.model_selection.GridSearchCV(estimator, param_grid, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score='raise')
    对估计器的指定参数值进行详尽搜索
    estimator：估计器对象
    param_grid：参数网格，字典类型
    cv: 指定几折交叉验证
    fit: 输入训练数据
    score: 准确率
        结果：
        best_score_： 最佳准确率
        bestestimator： 最佳参数模型
        cvresults： 每次交叉验证后的验证集准确率结果和训练集准确率结果 

In [ ]:
# 回归问题

from sklearn.neighbors import KNeighborsRegressor


#  数据集
#   平方和
#   开根号
#   差值：
x_train = [[0, 0, 1], [1, 1, 0], [3, 10, 10], [4, 11, 12]]
y_train = [0.1, 0.2, 0.3, 0.4]
x_test = [[3, 11, 10]]

## 创建回归模型
estimator = KNeighborsRegressor(n_neighbors=2)

## 模型训练
estimator.fit(x_train, y_train)

## 模型预测
y_pre = estimator.predict(x_test)

print(f'预测结果为：{y_pre}')

预测结果为：[0.35]


##  特征归一化处理

from sklearn.preprocessing import MinMaxScaler

x_train = [[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 13, 46]]

## feature_range 表示生成范围，默认[0,1]，默认可不写
scaler = MinMaxScaler(feature_range=(0, 1))

## 对数据进行归一化处理
x_train_new = scaler.fit_transform(x_train)

print(x_train_new)

##  特征标准化

[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.83333333]
 [0.5        0.5        0.6        1.        ]]


## 特征标准化

from sklearn.preprocessing import StandardScaler

x_train = [[90, 2, 10, 40], [60, 4, 15, 45], [75, 3, 13, 46]]

transfer = StandardScaler()

x_train_new = transfer.fit_transform(x_train)

print('标准化后的数据集为：\n')
print(x_train_new)

print(f'数据集的均值：{transfer.mean_}')
print(f'数据集的方差：{transfer.var_}')
print(f'数据集的标准差：{transfer.scale_}')

标准化后的数据集为：

[[ 1.22474487 -1.22474487 -1.29777137 -1.3970014 ]
 [-1.22474487  1.22474487  1.13554995  0.50800051]
 [ 0.          0.          0.16222142  0.88900089]]
数据集的均值：[75.          3.         12.66666667 43.66666667]
数据集的方差：[150.           0.66666667   4.22222222   6.88888889]
数据集的标准差：[12.24744871  0.81649658  2.05480467  2.62466929]


# 通过KNN算法实现 鸢尾花的分类操作

机器学习的研发流程：
    1. 加载数据
    2. 数据的预处理
    3. 特征工程
    4. 模型训练
    5. 模型评估
    6. 模型预测

In [ ]:
## 鸢尾花数据集
from sklearn.datasets import load_iris
import pandas as pd
##根据 Seaborn 绘图
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split    # 数据集划分
from sklearn.neighbors import KNeighborsClassifier      # KNN分类器
from sklearn.preprocessing import StandardScaler        # 数据标准化
from sklearn.metrics import accuracy_score              # 模型评估，计算模型预测的准确性

# 数据加载
def dm01_load_iris():
    iris_data = load_iris()

    # print(f'数据集：{iris_data}')
    print(f'数据集：{iris_data.data[:5]}')
    print(f'标签集：{iris_data.target[:5]}')
    print(f'名称集：{iris_data.target_names}')
    print(f'特征集：{iris_data.feature_names}')
    # print(f'数据集描述：{iris_data.DESCR}')


# 数据可视化
def dm02_iris_data_visualization():
    iris_data = load_iris()
    ##  数据可视化
    iris_df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
    iris_df['label'] = iris_data.target
    # iris_data.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    # print(iris_df)
    
    sns.lmplot(x='sepal length (cm)', y='sepal width (cm)', hue='label', data=iris_df, fit_reg=False)
    plt.title('iris data')
    # plt.tight_layout()
    plt.show()


# 数据集划分
def dm03_split_train_test():
    iris_data = load_iris()
    # 从150个数据中150个特征中随机选择120个数据作为训练集，30个数据作为测试集
    x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=13)
    print(f'训练集特征：{x_train},  训练集：{x_train.shape}， 个数：{len(x_train)}')
    print(f'测试集特征：{x_test}, 测试集{x_test.shape}， 个数：{len(x_test)}')
    
def dm04_iris_evaluate_test():
    # 加载数据
    iris_data = load_iris()
    # 数据预处理
    x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=13)
    # 特征工程
    # 创建标准化对象
    transfer = StandardScaler()

    # fit_transform 兼具训练和转换的功能
    x_train= transfer.fit_transform(x_train)
    # transform 纯转换
    x_test = transfer.transform(x_test)


    # 模型训练
    estimator = KNeighborsClassifier(n_neighbors=3)
    estimator.fit(x_train, y_train)
    # 模型预测
    y_predict = estimator.predict(x_test)
    print(f'预测结果：{y_predict}')


    # 模型评估
    # 直接评分  基于：训练集的特征 和 训练集的标签
    print(f'真实结果：{estimator.score(x_test, y_test)}')
    # 基于：测试集的标签 和 预测的标签
    print(f'准确率：{accuracy_score(y_test, y_predict)}')





# dm01_load_iris()
# dm02_iris_data_visualization()
# dm03_split_train_test()

dm04_iris_evaluate_test()

预测结果：[1 1 0 2 2 0 2 2 0 1 2 1 1 0 2 0 2 2 1 0 1 0 0 2 1 2 0 2 1 2]
真实结果：0.9666666666666667
准确率：0.9666666666666667


## 交叉验证网格搜索

## 准确率最高，用全部数据（训练集 + 测试集）训练模型，再次用测试集对模型测试

In [ ]:
import torch
# 向量
# x = torch.arange(12)

# x.shape

# 元素数量标量
# x.numel()

# 三行四列分布
# x.reshape(3, 4)

# torch.zeros(2, 3, 4)

# x = torch.tensor([1.0, 2, 3, 8])
# y = torch.tensor([2, 2, 2, 2])

# x + y
# x * y
# x.sum()
# x - y
# x**y

# torch.exp(x)


X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# cat 连接
torch.cat([X, Y], dim=0)
# stack 堆叠
torch.cat([X, Y], dim=1)

X == Y

# 最后一行
X[-1]

# 第一行和第二行
X,X[1:3]
# 选定赋值
X[1, 2] = 9
X

X[0:2, :] = 12
X


# 内存问题，类似于c指针
before = id(X)

Y = Y + X
id(Y) == before


# 转换
A = X.numpy()
B = torch.tensor(A)
X, A



# print(x)

In [ ]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000')

import pandas as pd

# 读取刚才创建的数据
data = pd.read_csv(data_file)
data

# 演示如何处理缺失值
# print(data.isnull().sum())  # 查看每列缺失值数量
# 可能进行填充、删除等操作

# 如何处理缺失的数据 插值和删除
# 考虑插值
# !  inputs.mean()
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs
# 插值 用编码处理分类变量
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
# 用各列的平均值填充NaN值，此时数列中只剩下数值型变量
inputs = inputs.fillna(inputs.mean())
inputs

# 都是数值型变量，所以可以转化为张量格式
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

#t 现在就成功把一个CSV文件转化为一个张量格式了

     NumRooms Alley  Price
0       NaN  Pave  127500
1         2   NaN  106000
2         4   NaN  178100
3       NaN   NaN  140000


In [ ]:
A = torch.arange(20.).reshape(5, 4)
A
# 转置
A, A.T

# 多维
X = torch.arange(24).reshape(2, 3, 4)
X

# 两个矩阵按元素乘法称为 哈达玛浴   
B = A.clone()
B
A * B 
A
# sum 能对矩阵所有元素求和
A.shape, A.sum()

# 要mean浮点数
A.mean()

# 保持维度
sum_A = A.sum(axis=1, keepdim=True)
sum_A
# tensor([[ 6.],
#         [22.],
#         [38.],
#         [54.],
#         [70.]])

# sum_A = A.sum(axis=1, keepdim=False)
# sum_A
# tensor([ 6., 22., 38., 54., 70.])

# 广播机制
A / sum_A


# 点积
x = torch.arange(4.0)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y), torch.sum(x * y)

# 矩阵乘向量
A.shape, x.shape, torch.mv(A, x)

# 矩阵乘矩阵
B = torch.ones((4, 4))
B, torch.mm(A, B)

# 范数  向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u) 

# L1范数 向量元素绝对值的和
torch.abs(u).sum()

# 弗罗贝尼乌斯矩阵乘法 是矩阵元素的平方和的平方根
torch.ones((4, 9)), torch.norm(torch.ones((4, 9)))

# 按特定轴求和
a = torch.ones((2, 3, 4))
# 0轴求和
a, a.sum(axis=0)
# 1轴求和
a, a.sum(axis=1)
# 2轴求和
a, a.sum(axis=2)

# keepdims  保持维度
a.sum(axis=1, keepdim=True)

a.sum(axis=[1,2], keepdim=True)

**求导**

In [ ]:
import torch
x = torch.arange(4.)
x
# 存储梯度
x.requires_grad_(True)
x.grad  # 默认为None

# y = 2 * x**x
y = 2 * torch.dot(x, x)
y
y.backward()
x.grad
x.grad == 4 * x

# 在默认情况下，PyTorch会累积梯度，我们需要将梯度置零
# x.grad.zero_()
y = x.sum()
y.backward()
x.grad

# 对非标量调用`backward`需要传入一个向量作为参数，来指定`y`相对于多个变量的梯度，
# 例如，`y = x * x`，那么`y.backward(torch.ones(len(x)))`是等价的。 
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))

**线性回归**

In [ ]:
# 机器学习基础模型
# 基础线性回归算法优化

import random
import torch
import torch.nn as nn
import numpy as np
# from d2l import torch as d2l
import d2l

# 根据带有噪声的线性模型构造数据集。设数据集大小为n，批量大小为batch_size。
# 生成批量数据
def synthetic_data(w, b, num_examples):
    """生成 y = Xw + b + 噪声"""
    # 生成一个形状为(num_examples, len(w))的随机正态分布张量，均值为0，标准差为1
    # 这代表特征矩阵X，每一行是一个样本，每一列是一个特征
    X = torch.normal(0, 1, (num_examples, len(w)))
    # 计算线性模型的基本预测值：X与权重w相乘再加上偏置b
    y = torch.matmul(X, w) + b
    # 添加高斯噪声，模拟真实数据中的不确定性
    # 噪声的标准差为0.01，使数据更接近实际情况
    y += torch.normal(0, 0.01, y.shape)
    # 将y重新塑形为(-1, 1)，即保持行数不变，列数变为1
    # 这样确保标签y是一个列向量
    return X, y.reshape((-1, 1))

# 定义真实的权重参数，这是我们要学习的目标参数
# w = [2, -3.4] 表示第一个特征的权重为2，第二个特征的权重为-3.4
true_w = torch.tensor([2, -3.4])
# 定义真实的偏置参数，这是线性模型中的截距项
true_b = 4.2
# 使用定义的参数生成包含1000个样本的人工数据集
# features是特征矩阵，labels是对应的标签
features, labels = synthetic_data(true_w, true_b, 1000)

print('features:', features[0], '\nlabel:', labels[0])

d2l.set_figsize()
d2l.plt.scatter(features[:, 1].detach().numpy(),
                labels.detach().numpy(), 1)


# 定义一个data_iter函数，接受批量大小、特征矩阵和标签向量作为输入
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

bathch_size = 10

for X, y in data_iter(bathch_size, features, labels):
    print(X, '\n', y)
    break

# 定义一个线性模型
def linreg(X, w, b):
    """线性回归模型"""
    return torch.matmul(X, w) + b

# 定义初始化模型参数
w = torch.normal(0, 0.01, size=(2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True) 

# 定义一个损失函数
def squared_loss(y_hat, y):
    """均方损失"""
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2

# 定义优化算法
def sgd(params, lr, batch_size):
    """小批量随机梯度下降"""
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

# 开始学习
lr = 0.03           # 学习率
num_epochs = 3      # 迭代轮数
net = linreg        # 模型
loss = squared_loss # 损失函数

for epoch in range(num_epochs):     # 迭代数据集
    for X, y in data_iter(bathch_size, features, labels):       # 迭代批量
        l = loss(net(X, w, b), y) # 计算损失
        # 因为l形状是(batch_size, 1)，而不是一个标量
        # 所以sum()函数会返回一个标量
        l.sum().backward()
        sgd([w, b], lr, bathch_size) # 优化模型参数
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

features: tensor([-1.3889,  0.8453]) 
label: tensor([-1.4672])
tensor([[-0.7572, -0.0395],
        [ 0.8483,  1.7406],
        [-0.1765, -0.7601],
        [-0.2602, -0.6211],
        [ 0.5851, -0.0517],
        [ 1.5804,  1.3608],
        [-1.0579, -1.7516],
        [ 0.1545,  0.4167],
        [-1.1077, -0.2291],
        [-0.2758,  1.4981]])
 tensor([[ 2.8269],
        [-0.0222],
        [ 6.4254],
        [ 5.7961],
        [ 5.5406],
        [ 2.7194],
        [ 8.0233],
        [ 3.0914],
        [ 2.7633],
        [-1.4430]])
epoch 1, loss 0.048619
epoch 2, loss 0.000201
epoch 3, loss 0.000048


**概率**

In [ ]:
import d2l
import torch
from torch.distributions import multinomial

fair_probs = torch.ones([6]) / 6





**线性回归的简单实现**

In [ ]:
import numpy as np
import torch
from torch.utils import data
import d2l

true_w = torch.tensor([2.0, -3.4])
true_b = 4.2

# 生成数据
features, labels = d2l.synthetic_data(true_w, true_b, 1000)


 
